### ISSUE TITLE
Ton compte omnivox est exposé

### ISSUE THREAD

**Issue by yanimeziani** [Simon-Petit/Horaire-Omnivox#2]
Dans ton scraper tu à laissé ton compte omnivox en clair. Je te conseille vivement de le changer.

**Comment by Simon-Petit** [comment]
J'avais oublié que c'était sur GitHub... Merci de me l'avoir partagé. J'ai déjà changé mon mot de passe et je vais mettre à jour le repository. De : Yani MezianiEnvoyé le :Wednesday, May 3, 2023 8:44 PMÀ : Simon-Petit/Horaire-OmnivoxCc : SubscribedObjet :[Simon-Petit/Horaire-Omnivox] Ton compte omnivox est exposé (Issue #2) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by yanimeziani** [comment]
Parfait ! Bonne journée à toi.
